### ISSUE TITLE
[transaction/list]Optimization: The page refresh wait time is too long after the last page button is clicked

### ISSUE THREAD

**Issue by 15168316096** [Magickbase/ckb-explorer-public-issues#119]
https://explorer.nervos.org/transaction/list?page=322177&size=25
click the last button ,  but respone time is too long，cost 1.7min
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/45781590/206416857-6c2cbd39-5d00-4ffa-a27b-8abf115e9ceb.png">

**Comment by ShiningRay** [comment]
This page number is too large 322177.
This will slow down the database signficantly.
Because our pagination mechinism is use SQL's `offset` and `limit`
The `offset` actually discard and skip the preceding records, so it's very slow on large dataset and large page.
I suggest we shall limit the large page no query, and use additional query conditions like datetime range to restrict the size of dataset.

**Comment by ShiningRay** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1126

**Comment by Keith-CY** [comment]
Max page number will be limited to 5000 in front-end

**Comment by Keith-CY** [comment]
Front-end PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1188
