### ISSUE TITLE
Strange hash rate chart

### ISSUE THREAD

**Issue by Flouse** [Magickbase/ckb-explorer-public-issues#254]
![image](https://user-images.githubusercontent.com/1297478/229571515-42e4305a-ad03-48a2-b0ea-f7ccf7ae62aa.png)
https://explorer.nervos.org/charts/hash-rate

![image](https://user-images.githubusercontent.com/1297478/229571663-cbc454ab-9e49-4496-b947-7e7cdd689f11.png)
https://explorer.nervos.org/

**Comment by Keith-CY** [comment]
It was caused by an unhandled exception in generating statistical data. The exception was improperly handled and left a zero point in most charts, as shown in the screenshot.

We've started two solutions
1. break calculations down so they will not be affected by each other, and only one chart will incorrect: https://github.com/Magickbase/ckb-explorer-public-issues/issues/228
2. add a monitor when the calculation fails: https://github.com/Magickbase/ckb-explorer-public-issues/issues/252
