### ISSUE TITLE
Nervos Dao page total_dao_deposit is different with daily statistic tables

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/ckb-explorer-public-issues#293]
~~After research, We found that daily_statistic's tables lost some data.The data's date are` 2022-11-27 2022-11-28 2022-11-29 2022-11-30`.
So when jump to 2022-12-1, the daily_statistic's  total_dao_deposit value has a big difference suddenly.~~

|table| total_dao_deposit|date|
|----|---|----|
|daily_statistics|819167703853365805|2022-12-1
|dao_events|844409563603513339|2022-12-1
- - -
Update：
2022-11-27,2022-11-28,2022-11-29,2022-11-30, 2022-12-03 date's data not lost. The created unix timestamp were different with others.
Most tables data were created at 16:00 UTC, but these date were save at 00:05(the job run at).
So maybe these date's schedule job were not run automatically but run manually.

**Comment by Keith-CY** [comment]
![image](https://user-images.githubusercontent.com/7271329/232726798-b3202dc7-a73d-4b79-a581-19da4c37b0e4.png)

Zoomed in
![image](https://user-images.githubusercontent.com/7271329/232726978-2d5ba162-bb08-457d-afd3-981deb4d1c5c.png)
![image](https://user-images.githubusercontent.com/7271329/232727104-fb38bd2e-0bbd-4d1b-994f-803ed9733e45.png)

2.24G CKB and 0.01K addresses are lost in the chart

**Comment by zmcNotafraid** [comment]
link https://github.com/Magickbase/ckb-explorer-public-issues/issues/296

**Comment by Keith-CY** [comment]
It takes a long time to regenerate the historical data with the current codebase, 0.5~1 hour for 1 day. So it's expected to take 500 ~ 1000 hours to regenerate the whole history.

And it cannot be generated from the `daily deposit` chart because they are defined differently.
`total deposit = sum(daily deposit) - sum(daily withdrawal)` while `daily deposit` only covers `deposit`, excluding `withdrawal`

Any idea about fixing the historical data. @zmcNotafraid @ShiningRay @zhengjianhui @Danie0918 @Sven-TBD 

My thought is to fix the data in 2 parts
1. Fix today's data to reflect the correct status of future
2. Fix the historical data after the refactor(https://github.com/Magickbase/ckb-explorer-public-issues/issues/272) is done, which stores `nervos dao status` of every block so the historical data will be regenerated.
