### ISSUE TITLE
The data display in the transaction list is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#316]
By default, the transaction list uses 10 pieces of data per page, and now only the first 20 pieces (2 pages) of 38 pieces of data are displayed, and the subsequent data cannot be previewed.
https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqt4u5aeg79q485ppxs7d5905uqmf4j09rqjz3dce

interface information:
`Request URL: https://mainnet-api.explorer.nervos.org/api/v1/address_transactions/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqt4u5aeg79q485ppxs7d5905uqmf4j09rqjz3dce?page=1&page_size=10`
<img width="1212" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/5a9b1385-d2a9-4929-abb7-200fe2da2be6">

We can view the complete data by adding `?page=1&size=100` in the url.
https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqt4u5aeg79q485ppxs7d5905uqmf4j09rqjz3dce?page=1&size=100

Is it related to the items value in the interface?
<img width="1422" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/83a1c9f1-6411-4f0c-a192-e388f029c2d5">

**Comment by rabbitz** [comment]
1. This paging is not related to the paging information in the interface https://mainnet-api.explorer.nervos.org/api/v2/nft/items?owner=ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqt4u5aeg79q485ppxs7d5905uqmf4j09rqjz3dce&standard=cota
2. The paging parameter in the interface (https://mainnet-api.explorer.nervos.org/api/v1/address_transactions/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqt4u5aeg79q485ppxs7d5905uqmf4j09rqjz3dce?page=2&page_size=10) is `page_size`, but the paging parameter defined in the front-end interface is `size` (https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/utils/hook.ts#L218) . Since the size parameter in the url does not exist, `defaultPageSize` ( https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/pages/Address/AddressComp.tsx#L315) is taken as the default value. Here, the default value of paging is defined as 25 records (https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/utils/hook.ts#L271).

**Comment by zhb666** [comment]
1. The frontend page does not have an option to set the number of displayed data entries. Upon reflection, it seems that the setting may be too large, causing both the frontend and backend to become unresponsive.
2. If the URL is in the format of `xxx?page=2&size=10`, the parameters are valid, and the `size` does not exceed 100 data entries, the page will display the data correctly. The default maximum `size` is 100.
3. By default, the frontend displays 25 data entries. If there are manually input parameters in the URL, the page will read and display the corresponding number of entries.


After conducting research and analysis, it has been concluded that the issue occurred due to an invalid parameter, specifically the `page_size` parameter being entered in the browser's URL input field. The logic implemented to handle this situation is correct. It is important to note that the `size` parameter in the URL is typically a standardized parameter, and it should not match any arbitrary parameter value. Allowing arbitrary parameter values would be abnormal and not allowed.

**Comment by Danie0918** [comment]
It will be done in ：https://github.com/Magickbase/ckb-explorer-public-issues/issues/356
