### ISSUE TITLE
Lots of Pending Transactions listed in `transaction/list?tab=pending`

### ISSUE THREAD

**Issue by Flouse** [Magickbase/ckb-explorer-public-issues#380]
<img width="621" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/1297478/e5a1d05f-3264-4293-bb98-9cdac5b80141">
https://explorer.nervos.org/transaction/list?tab=pending

### Is it an expected behavior?

**Comment by Keith-CY** [comment]
It should be fixed by https://github.com/Magickbase/ckb-explorer-public-issues/issues/348, but the unexpected behavior is still there cc @Danie0918 

Ref: https://pudge.explorer.nervos.org/transaction/list?tab=pending
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/475874de-132a-4894-8fa0-11bcdcd1ea67)
