### ISSUE TITLE
Data with abnormal creation time prompts 404 on the details page interface.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#416]
https://pudge.explorer.nervos.org/tokens?sort=created_time.asc
<img width="1337" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/01b1ea1e-15c5-4e91-bc2a-fe6e624ba169">

Click to enter the token details page, and the interface displays 404.
https://pudge.explorer.nervos.org/sudt/0x935037492ef981da59d2560868a243f5073e0776c242a0088951f63e64e53353
`Request URL: https://testnet-api.explorer.nervos.org/api/v1/udts/0x935037492ef981da59d2560868a243f5073e0776c242a0088951f63e64e53353`

<img width="1430" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/26b68968-dda5-42b8-987f-18f6d4f8d862">

**Comment by rabbitz** [comment]
1.  This `Created Time 1970-01-19` is displayed because the unit of the block_timestamp field saved in some sudt type data (time range `2020-10-27` to `2021-08-10` ) is seconds, which should actually be milliseconds. So the front end is formatted wrong. The data has been updated.

2. Data with the script type `0x935037492ef981da59d2560868a243f5073e0776c242a0088951f63e64e53353` is excluded due to incomplete information, and therefore, the frontend should not display it.

https://github.com/nervosnetwork/ckb-explorer/blob/develop/app/controllers/api/v1/udts_controller.rb#L48

**Comment by PainterPuppets** [comment]
related pr: https://github.com/Magickbase/ckb-explorer-frontend/pull/98

**Comment by FrederLu** [comment]
Verified.
