### ISSUE TITLE
Transactions using countdown are missing alarm clock icon.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#465]
1. When the countdown is in progress, the alarm clock icon needs to be displayed to the right of the corresponding input/output address, and the mouse hover icon displays the countdown details.
2. The icon needs to be hidden after the countdown is over.

https://pudge.explorer.nervos.org/transaction/0xd9b8e135de3c1fe598b73b42ea71888269f5fac01c3d08f4904fa3bf95a088bb
<img width="1439" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/61fdeaba-d3aa-46d6-b207-a6f619f87838">
<img width="1311" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/9942482d-a437-428a-a40b-46937ff72e89">

<img width="1084" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/76b35215-73ea-44b1-a431-dd5037d5db61">

**Comment by Daryl-L** [comment]
I didn't find the `since` property in `display_outputs` which is responded by api `/transactions/:hash`

**Comment by Sven-TBD** [comment]
I think the cell in the outpoint should also be marked if the cell in the output does have a lock time.  @Keith-CY @zmcNotafraid @FrederLu 
The purpose of the alarm clock icon is to show users some cells need time to unlock. Starting from the logic of the icon itself, which is to mark the status of the cell regardless of whether it is an input or an output, we should know that if the cell in the outpoint has the attribute of a lock time, then it should be displayed as well. If this issue is a little bit complex, we can start another issue specifically to track it.

ZH-CN
我认为outpoint 中的cell 如果有lock time 也应当被标出。这里的闹钟 icon 是为了向用户展示，icon 所标出的Cell 还有多久unlock。从icon本身的逻辑出发，即icon是为了标注cell的状态，而与是否input还是output无关。那么如果outpoint 中的cell 具有lock time的属性就应到被展示出来。如果这个问题比较复杂，可以另起一个issue专门追踪。

**Comment by Sven-TBD** [comment]
> Document about `since` at https://github.com/nervosnetwork/rfcs/blob/01f3bc64ef8f54c94c7b0dcf9d30c84b6c8418b0/rfcs/0017-tx-valid-since/0017-tx-valid-since.md#transaction-since-precondition

@FrederLu @Keith-CY 
According to the RFC and the current design, we can know that :

1. The current clock icon is designed for the `since` attribution of a cell which only shows in the inputs.
2. This issue put by Lu refers to the missing of the clock icon for the `locktime` function of a cell in the output set, so we can add another color of the clock icon for the `locktime` feature. And this could be tracked in a new issue.
