### ISSUE TITLE
Request to an address returns 404

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#75]
Page: https://explorer.nervos.org/address/ckb1qqypm0l63rdt2jayymfrrjnyadmqe630a8skwcdpmfqqmgdje0sjsqggcmymq4q8vr285esldae6fdz5uckjrgct04n7r

Request:
https://mainnet-api.explorer.nervos.org/api/v1/addresses/ckb1qqypm0l63rdt2jayymfrrjnyadmqe630a8skwcdpmfqqmgdje0sjsqggcmymq4q8vr285esldae6fdz5uckjrgct04n7r

![image](https://user-images.githubusercontent.com/7271329/194691706-f4e671cf-8c34-4441-83c4-f03178cb10ec.png)

**Comment by ShiningRay** [comment]
This is because the record of address '[ckb1qqypm0l63rdt2jayymfrrjnyadmqe630a8skwcdpmfqqmgdje0sjsqggcmymq4q8vr285esldae6fdz5uckjrgct04n7r](https://mainnet-api.explorer.nervos.org/api/v1/addresses/ckb1qqypm0l63rdt2jayymfrrjnyadmqe630a8skwcdpmfqqmgdje0sjsqggcmymq4q8vr285esldae6fdz5uckjrgct04n7r)' does not have corresponding lock script record.
I have fix this data.

**Comment by Keith-CY** [comment]
Please add a brief explanation that why the address doesn't have a corresponding lock script record so we can find the source of this issue

**Comment by Keith-CY** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1031
